### ISSUE TITLE
Not working with webpack 5

### ISSUE THREAD

**Issue by vijaypemmaraju** [mohsen1/service-worker-loader#141]
Just upgraded to the webpack 5 beta and I'm seeing this error:

```
ERROR in ./src/serviceWorkers/firebase-messaging.worker.js
Module build failed (from ./node_modules/service-worker-loader/lib/index.js):
TypeError: Cannot assign to read only property 'cache' of object '#<Compilation>'
    at compilation (/Users/vijaypemmaraju/febes/node_modules/service-worker-loader/lib/index.js:141:25)
    at Hook.eval [as call] (eval at create (/Users/vijaypemmaraju/febes/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:111:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/vijaypemmaraju/febes/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/vijaypemmaraju/febes/node_modules/webpack/lib/Compiler.js:865:26)
    at hooks.beforeCompile.callAsync.err (/Users/vijaypemmaraju/febes/node_modules/webpack/lib/Compiler.js:905:29)
    at Hook.eval [as callAsync] (eval at create (/Users/vijaypemmaraju/febes/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vijaypemmaraju/febes/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/vijaypemmaraju/febes/node_modules/webpack/lib/Compiler.js:900:28)
    at Compiler.runAsChild (/Users/vijaypemmaraju/febes/node_modules/webpack/lib/Compiler.js:445:8)
    at Object.pitch (/Users/vijaypemmaraju/febes/node_modules/service-worker-loader/lib/index.js:148:12)
```

I know webpack 5 is still in beta, but is this something that can be easily resolved?

**Comment by blasterpistol** [comment]
Feels like no loader need now https://webpack.js.org/blog/2020-10-10-webpack-5-release/#native-worker-support

**Comment by soryy708** [comment]
Perhaps related? https://github.com/mohsen1/service-worker-loader/issues/340
